# Generated by Django 4.0.3 on 2022-04-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='basket',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.basket'),
        ),
    ]
