# Generated by Django 4.0.3 on 2022-03-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.catalogy'),
        ),
    ]
