# Generated by Django 4.0.3 on 2022-04-22 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_has_packages_remove_products_package_and_more'),
        ('main', '0002_alter_users_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_cost', models.DecimalField(decimal_places=0, max_digits=7)),
                ('comment', models.TextField()),
                ('id_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.basket')),
            ],
        ),
        migrations.CreateModel(
            name='orders_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.products')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(through='main.orders_list', to='goods.products'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.paymant_method'),
        ),
        migrations.AddField(
            model_name='order',
            name='point_of_issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.point_of_issue'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiving_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.receiving_method'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
