# Generated by Django 4.0.3 on 2022-04-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_basket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='orders',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
        ),
    ]
