# Generated by Django 4.0.3 on 2022-04-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_has_packages_remove_products_package_and_more'),
        ('main', '0003_order_orders_list_order_order_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.package'),
        ),
        migrations.AlterField(
            model_name='users',
            name='basket',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.basket'),
        ),
    ]
