# Generated by Django 4.0.3 on 2022-04-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='basket',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.basket'),
        ),
    ]
