# Generated by Django 4.0.3 on 2022-04-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_users_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='basket',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
