# Generated by Django 4.0.3 on 2022-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
