# Generated by Django 4.0.3 on 2022-04-23 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_has_packages_remove_products_package_and_more'),
        ('main', '0010_alter_basket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.package'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
