# Generated by Django 4.0.3 on 2022-04-26 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_image_options_alter_package_options_and_more'),
        ('main', '0014_alter_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Товары корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.paymant_method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='point_of_issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.point_of_issue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiving_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.receiving_method'),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.package'),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products'),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(null=True)),
                ('grade', models.SmallIntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
