# Generated by Django 4.0.3 on 2022-04-27 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_comments_options_alter_comments_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='grade',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
