# Generated by Django 4.0.3 on 2022-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_comments_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_list',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
