# Generated by Django 4.0.3 on 2022-04-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_orders_list_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_basket',
        ),
    ]
