# Generated by Django 4.0.4 on 2022-05-01 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=7)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.image')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='product_has_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.package')),
            ],
        ),
        migrations.CreateModel(
            name='product_has_section_and_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
            ],
        ),
        migrations.CreateModel(
            name='section_and_caterogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.section_and_caterogy')),
            ],
            options={
                'verbose_name': 'Секции и катогории',
                'verbose_name_plural': 'Секции и категории',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('discription', models.TextField(default='')),
                ('discount', models.IntegerField(default=0)),
                ('purpose', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='', max_length=45)),
                ('manufacturer', models.CharField(default='', max_length=45)),
                ('best_before_date', models.DateField(default='')),
                ('composition', models.CharField(default='', max_length=255)),
                ('number_of_views', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(through='goods.product_has_section_and_category', to='goods.section_and_caterogy')),
                ('package', models.ManyToManyField(through='goods.product_has_packages', to='goods.package')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.rating')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='product_has_section_and_category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products'),
        ),
        migrations.AddField(
            model_name='product_has_section_and_category',
            name='section_and_caterogy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.section_and_caterogy'),
        ),
        migrations.AddField(
            model_name='product_has_packages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products'),
        ),
    ]
