# Generated by Django 4.0.3 on 2022-04-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caterogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=7)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='goods.image')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('discription', models.TextField(default='')),
                ('discount', models.IntegerField(default=0)),
                ('purpose', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='', max_length=45)),
                ('manufacturer', models.CharField(default='', max_length=45)),
                ('best_before_date', models.DateField(default='')),
                ('composition', models.CharField(default='', max_length=255)),
                ('rating', models.FloatField(default=0)),
                ('number_of_views', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='goods.caterogy')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.package')),
            ],
        ),
        migrations.AddField(
            model_name='caterogy',
            name='section',
            field=models.ManyToManyField(to='goods.section'),
        ),
    ]
