# Generated by Django 4.0.3 on 2022-04-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='package',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='goods.package'),
        ),
    ]
