# Generated by Django 4.0.3 on 2022-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(through='goods.product_has_section_and_category', to='goods.section_and_caterogy'),
        ),
    ]
