# Generated by Django 4.0.3 on 2022-04-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_products_category_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_has_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.package')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='package',
        ),
        migrations.AddField(
            model_name='products',
            name='package',
            field=models.ManyToManyField(through='goods.product_has_packages', to='goods.package'),
        ),
        migrations.AddField(
            model_name='product_has_packages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.products'),
        ),
    ]
