# Generated by Django 4.0.3 on 2022-04-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_package_image_image_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='goods.image'),
        ),
    ]
