# Generated by Django 4.0.3 on 2022-04-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Пакет', 'verbose_name_plural': 'Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='section_and_caterogy',
            options={'verbose_name': 'Секции и катогории', 'verbose_name_plural': 'Секции и категории'},
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.image'),
        ),
        migrations.AlterField(
            model_name='product_has_packages',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.package'),
        ),
        migrations.AlterField(
            model_name='product_has_packages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products'),
        ),
        migrations.AlterField(
            model_name='product_has_section_and_category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products'),
        ),
        migrations.AlterField(
            model_name='product_has_section_and_category',
            name='section_and_caterogy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.section_and_caterogy'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.rating'),
        ),
    ]
